---
version: "2.1"
services:
  baserow:
    image: baserow/baserow:1.13.3
    container_name: baserow
    environment:
      - TZ=Australia/Brisbane
    volumes:
      - /portainer/Files/AppData/Config/baserow:/baserow/data
    ports:
      - 280:80  #changed from default 80
      - 2443:443
    restart: unless-stopped